config/routes.rb
Rails.application.routes.draw do

  get 'calculations/new'

  root 'pages#home'
  get     '/signup',    to: 'users#new'

  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'

  resources :users

  resources :calculations, only: [:create, :show, :destroy] do
    member do
      get :show_original_image
      get :kill_calculation_process
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord

  belongs_to :user
  mount_uploader :inputFile, FileUploader

  serialize :mass,                          Array
  serialize :height,                        Array
  serialize :inertia,                       Array
  serialize :omega,                         Array
  serialize :beta,                          Array
  serialize :proportional_gain,             Array
  serialize :derivative_gain,               Array
  serialize :time_delay,                    Array
  serialize :sensory_weighting_parameter,   Array
  serialize :tau,                           Array
  serialize :force_gain,                    Array
  serialize :gof_body_sway,                 Array
  serialize :gof_torque,                    Array
  serialize :gof_emg,                       Array

  validates :bodyWeight,  presence: true
  validates :bodyLength,  presence: true
  validates :inputFile,   presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :calculations, dependent: :destroy

  before_save { self.email = email.downcase}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  presence: true,
                    length: { maximum: 50 }

  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?   BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  include SessionsHelper

  def logged_in_user
    if(current_user.nil?)
      redirect_to login_path
    end
  end

  def correct_user?(user_id)
    if(current_user.present?)
      redirect_to current_user if user_id.to_i != current_user.id
    end
  end

end

app/controllers/calculations_controller.rb
require 'calculation_runner'
class CalculationsController < ApplicationController

  before_action :correct_user, only: [:show, :destroy, :show_original_image, :kill_calculation_process]
  before_action :logged_in_user

  def create
    @calculation = current_user.calculations.build(calculation_params)
    if(@calculation.save)
      CalculationRunner.calculate(@calculation)
      redirect_to root_path
    else
      @calculations = current_user.calculations
      render 'pages/home'
    end
  end

  def show
    @calculation = Calculation.find_by(id: params[:id])
  end

  def show_original_image
    @calculation = Calculation.find_by(id: params[:id])
  end

  def destroy
    @calculation = Calculation.find_by(id: params[:id])
    if(@calculation.present?)
      CalculationRunner.delete_calculation_data(@calculation)
      @calculation.destroy
      redirect_to root_path
    end
  end

  def kill_calculation_process
    @calculation = Calculation.find_by(id: params[:id])
    if(@calculation.present?)
      CalculationRunner.kill_calculation_process(@calculation)
      @calculation.destroy
      redirect_to root_path
    end
  end

  private

  def correct_user
    user = Calculation.find_by(id: params[:id]).user
    correct_user?(user.id)
  end

  def calculation_params
    params.require(:calculation).permit(:bodyWeight, :bodyLength, :inputFile)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if(is_logged_in?)
      @calculation = current_user.calculations.build
      @calculations = current_user.calculations
    end
  end
end

app/controllers/sessions_controller.rb
require 'sessions_helper'
class SessionsController < ApplicationController

  def new
    render 'new'
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if(user && user.authenticate(params[:session][:password]))
      log_in(user)
      redirect_to root_path
    else
      flash.now[:danger] = "Wrong email or password!"
      render 'new'
    end
  end

  def destroy
    if(is_logged_in?)
      log_out
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account created"
      log_in(@user)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find(params[:id])
    if(@user.update_attributes(user_params))
      flash[:success] = 'Succesfully updated!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def correct_user
    correct_user?(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper

  def full_title(title = "")
    base_title = 'BalanceControlTool'
    if(title.empty?)
      base_title
    else
      title + " | " + base_title
    end
  end
end

app/helpers/calculations_helper.rb
module CalculationsHelper
  require 'calculation_runner'
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def is_logged_in?
    current_user.present?
  end

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.name, class: "gravatar")
  end
end

app/views/calculations/_calculation.html.erb
<tr>
  <td> <%= calculation.bodyWeight %> </td>
  <td> <%= calculation.bodyLength %> </td>
  <% if(calculation.jobStatus.equal?(true)) %>
      <td>
        <%= link_to CalculationRunner.calculation_output_results_path(calculation).to_s do %>
          <span class="glyphicon glyphicon-download-alt"></span>
        <% end %>
        <%= link_to calculation do %>
            <span class="glyphicon glyphicon-eye-open"></span>
        <% end %>
        <%= link_to calculation, method: :delete do %>
            <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </td>
  <% else %>
      <td>
        <i class="fa fa-gear fa-spin" style="font-size:24px;"></i>
        <%= link_to kill_calculation_process_calculation_path(calculation) do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </td>
<% end %>
</tr>

app/views/calculations/show.html.erb
<head>
  <!--Load the AJAX API-->
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">

    // Load the Visualization API and the corechart package.
    google.charts.load('current', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

      // Create the data table.
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Topping');
      data.addColumn('number', 'Slices');
      data.addRows([
        ['Mushrooms', 3],
        ['Onions', 1],
        ['Olives', 1],
        ['Zucchini', 1],
        ['Pepperoni', 2]
      ]);

      // Set chart options
      var options = {'title':'How Much Pizza I Ate Last Night',
        'width':400,
        'height':300};

      // Instantiate and draw our chart, passing in some options.
      var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
  </script>
</head>
<div class="row center">
  <%= link_to image_tag(CalculationRunner.calculation_output_image_path(@calculation)), show_original_image_calculation_path(@calculation.id) %>

  <div class="container">
    <div class="jumbotron center">
      <div class="row">
        <div class="col-md-12 col-centered">
          <table class="table table-hover table-calculation-results">

            <thead>
              <tr>
                <td class="table-calculation-results-first-col">Parameter</td>
                <td> Eyes open - 0.5 degrees </td>
                <td> Eyes open – 1.0 degrees </td>
                <td> Eyes closed – 0.5 degrees </td>
                <td> Eyes closed – 1.0 degrees </td>
              </tr>
            </thead>

            <tbody>
              <% @calculation.attributes.each do |attr_name, attr_val| %>
                <% if attr_val.class.to_s == "Array" %>
                    <tr>
                      <td class="table-calculation-results-first-col"> <%= attr_name.to_s.gsub("_", " ").capitalize %> </td>
                      <td> <%= attr_val[0] %> </td>
                      <td> <%= attr_val[1] %> </td>
                      <td> <%= attr_val[2] %> </td>
                      <td> <%= attr_val[3] %> </td>
                    </tr>
                <% end %>
              <% end %>
            </tbody>

          </table>
        </div>
        <div id="char_div"></div>
      </div>
    </div>
  </div>
</div>

app/views/calculations/show_original_image.html.erb
<%= link_to image_tag(CalculationRunner.calculation_output_image_path(@calculation, true)), @calculation %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>"> EMBalance </a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="<%= root_path %>">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if is_logged_in? %>
          <li class="dropdown">
            <a class = "dropdown-toggle" data-toggle="dropdown" href="#"> <span class="caret"></span> Account </a>
            <ul class="dropdown-menu">
              <li> <%= link_to 'Profile', user_path(current_user) %> </li>
              <li> <%= link_to 'Settings', edit_user_path(current_user) %> </li>
              <li class='divider'></li>
              <li> <%= link_to 'Log out', logout_path, method: 'delete' %> </li>
            </ul>
          </li>
      <% else %>
        <li><a href="<%= signup_path %>"><span class="glyphicon glyphicon-user"></span>Sign up</a></li>
        <li><a href="<%= login_path %>"> <span class="glyphicon glyphicon-log-in"></span>Log in</a></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="refresh" content="60" />
    <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<head>
</head>
<%= provide(:title, "Home") %>
<div class="container">
  <div class="center jumbotron">
    <% if is_logged_in? %>
        <div class="row">
          <div class="col-md-3 col-centered">
            <h3> Balance Control Tool </h3>
              <%= render 'shared/form_calculations' %>
          </div>
        </div>
        <table class="table table-hover">

          <thead>
            <tr>
              <th>Body Weight</th>
              <th>Body Length</th>
              <th>Calculation</th>
            </tr>
          </thead>

          <tbody>
            <%= render @calculations %>
          </tbody>

        </table>
    <% else %>
      <h3> Balance Control Tool </h3>
      <%= link_to "Sign up", signup_path, class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.present? %>
    <div class="alert alert-danger">
      The form contains <%=  pluralize(object.errors.count, 'error') %>
    </div>
    <% object.errors.full_messages.each do |msg| %>
      <ul>
        <li> <%= msg %> </li>
      </ul>
    <% end %>
<% end %>

app/views/shared/_form_calculations.html.erb
  <%= form_for(@calculation, html: { multipart: true }) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label       'Body weight' %>
      <%= f.text_field  :bodyWeight, class: 'form-control' %>

      <%= f.label       'Body Length' %>
      <%= f.text_field  :bodyLength, class: 'form-control' %>

      <%= f.file_field :inputFile %>

      <%= f.submit 'Start', class: 'btn btn-success' %>

  <% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>

    <%= f.submit yield(:btn_title), class: "btn btn-success" %>

<% end %>

app/views/users/edit.html.erb
<%= provide(:title, 'Update account') %>
<%= provide(:btn_title, 'Update account') %>
<div class="row user-info">
  <div class="col-md-3 col-md-offset-4">
    <%= render 'users/form' %>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:btn_title, "Create account") %>
<%= provide(:title, "Create account") %>
<div class="container">
  <div class="jumbotron center">
    <h3> Sign up </h3>
    <div class="row">
      <div class="col-md-6 col-centered">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-centered">
    <section class="user-info">
      <h1>
        <%= gravatar_for @user %>
        <%= "#{@user.name} | #{@user.email}"  %>
      </h1>
    </section>
  </div>
</div>